Create new resource: postgresql_grant
edgelaboratories/terraform-provider-postgresql pull request #6
Opened 2018-11-14 14:29 UTC by cyrilgdn

This resource allow to grant privileges on all existing tables or sequences
for a specified role in a specified schema.

2018-11-14 16:35 UTC, multani requested changes
Tests are good :+1: 

It's actually simpler than I originally thought, beside explaining what the query in `readRolePrivileges` does, it looks pretty good!

2018-11-14 16:35 UTC, multani commented on postgresql/helpers.go
> +// allowedPrivileges is the list of privileges allowed per object types in Postgres.
Is there an official documentation on the PostgreSQL website for what privileges can be given to what object?

2018-11-14 16:35 UTC, multani commented on postgresql/helpers.go
> +// startTransaction start a new DB transaction on the specified database.
```suggestion
// startTransaction starts a new DB transaction on the specified database.
```

2018-11-14 16:35 UTC, multani commented on postgresql/helpers.go
> +// If the database is specified and not the one configured in the provider,
Hum, this sentence is not clear.
I guess you meant: "If a database is specified and different from the one configured in the provider,"?

2018-11-14 16:35 UTC, multani commented on postgresql/helpers.go
> +	err := txn.QueryRow("SELECT datname from pg_database WHERE datname=$1", dbname).Scan(&dbname)
```suggestion
	err := txn.QueryRow("SELECT datname FROM pg_database WHERE datname=$1", dbname).Scan(&dbname)
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				Description: "The name of the role to which grant privileges",
```suggestion
				Description: "The name of the role to grant privileges on",
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				Description: "The database on which grant privileges for this role",
```suggestion
				Description: "The database to grant privileges on for this role",
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				ForceNew: true,
```suggestion
				ForceNew: true,
				Description: "The database schema to grant privileges on for this role",
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				ForceNew: true,
Shall it default to "public" BTW?

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				}, false),
```suggestion
				}, false),
				Description: "The PostgreSQL object type to grant the privileges on (one of: table, sequence)",
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				MinItems: 1,
```suggestion
				MinItems: 1,
				Description: "The list of privileges to grant",
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +SELECT pg_class.relname, array_remove(array_agg(privilege_type), NULL)
Do you think you can add a comment to explain that? :D
I don't think it needs to to into details, but mostly what the query checks and tries to find out (such as "The query parses the ACL for all the objects of the specified type for the given database/schema, blablabla")

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +			// If an object has not the same privileges as saved in the state,
```suggestion
			// If any object doesn't have the same privileges as saved in the state,
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +	// Check that role exists
```suggestion
	// Check the role exists
```

And same below

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +		log.Printf("[DEBUG] role %s does not exists", role)
```suggestion
		log.Printf("[DEBUG] role %s does not exist", role)
```

And same below

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +	// Check that schema exists ( be connected on the right database for that)
```suggestion
	// Check the schema exists (the SQL connection needs to be on the right database)
```

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +	if err := validatePrivileges(d.Get("object_type").(string), d.Get("privileges").(*schema.Set).List()); err != nil {
Can't this be done at the configuration level? (so I guess `terraform validate` would catch it)

2018-11-14 16:35 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +	// We just have to revoke them in the same transaction so role will not lost his privileges between revoke and grant.
```suggestion
	// We just have to revoke them in the same transaction so the role will not lost its privileges between the revoke and grant statements.
```

2018-11-14 16:36 UTC, multani commented on postgresql/testing.go
> +		Password: getEnv("PGPASSWORD", ""),
Oh and I had to add this here:

```
               SSLMode:  getEnv("PGSSLMODE", ""),
```

2018-11-14 17:11 UTC, cyrilgdn commented on postgresql/helpers.go
> +// allowedPrivileges is the list of privileges allowed per object types in Postgres.
Took it from https://www.postgresql.org/docs/current/sql-grant.html

2018-11-14 17:13 UTC, cyrilgdn commented on postgresql/resource_postgresql_grant.go
> +				ForceNew: true,
We can but I was a bit scared that it was not explicit that this will be applied on one schema only.

2018-11-14 17:19 UTC, cyrilgdn commented on postgresql/resource_postgresql_grant.go
> +	if err := validatePrivileges(d.Get("object_type").(string), d.Get("privileges").(*schema.Set).List()); err != nil {
Unfortunately no:

> ValidateFunc is not yet supported on lists or sets.

https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L193

2018-11-14 17:22 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +				ForceNew: true,
You are right, so let's keep it this way.

2018-11-14 17:23 UTC, multani commented on postgresql/helpers.go
> +// allowedPrivileges is the list of privileges allowed per object types in Postgres.
Maybe we can add a link to that doc in the comment.

2018-11-15 07:42 UTC, multani approved these changes
Still a few typo left.

2018-11-15 07:42 UTC, multani commented on postgresql/helpers.go
> +// If the database is specified and and different from the one configured in the provider,
```suggestion
// If the database is specified and different from the one configured in the provider,
```

2018-11-15 07:42 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +		// TODO: fill descriptions
```suggestion
```

2018-11-15 07:42 UTC, multani commented on postgresql/resource_postgresql_grant.go
> +	// Our goal is to check that every objects has the same privileges as saved in the state.
```suggestion
	// Our goal is to check that every object has the same privileges as saved in the state.
```

2018-11-15 15:04 UTC, merged